### ISSUE TITLE
Bi-Weekly Meeting

### ISSUE THREAD

**Issue by ShutingQing** [camaraproject/ClickToDial#8]
Hi Guys，

If you have interest, please leave a comment here. Let's discuss a suitable time for the bi-weekly meeting. Thanks.

BR, Shuting

**Comment by HanbaiWang** [comment]
How about this Wednesday afternoon (Beijing time)? I apologize, but I have meetings scheduled for this Thursday and Friday. If it's inconvenient for any of the maintainers, we can reschedule this meeting to next Tuesday through Friday.

**Comment by rartych** [comment]
Are the regular meeting for this subproject already scheduled?
I would like to join - from CET timezone.

**Comment by hdamker** [comment]
@ShutingQing @HanbaiWang Are there any meeting minutes yet (there is not link to them in the README.md, and I can't see them here in the repository). I'm asking as there where multiple PRs merged without any review or discussion.

**Comment by ShutingQing** [comment]
Hanbai was planning to hold a meeting this week. @DanXu-ChinaTelecom @HanbaiWang Let's choose an time suitable for the meeting. : ) I'll suggest on Friday Morning CET, Friday afternoon CST.

**Comment by ShutingQing** [comment]
@HanbaiWang Hanbai, how about have a meting after Qing Ming Festival?

**Comment by ShutingQing** [comment]
Closed, refer to https://github.com/camaraproject/ClickToDial/issues/15
